MODEL:
  TYPE:
  NAME: eva02_l_text
  PRETRAIN_PATH: '/home/jin/code/MADE/weights/eva02_large_patch14_clip_224/open_clip_model.safetensors'
  META_DIMS: [ 105, ]
  METRIC_LOSS_TYPE: 'triplet'
  IF_LABELSMOOTH: 'off'
  IF_WITH_CENTER: 'no'
  NO_MARGIN: True
  DEVICE_ID: ('0')
  ADD_META: False
  MASK_META: False
  DIST_TRAIN: False
  ADD_TEXT: True
  TEXT_DIMS: [ 512, ]
  TEXT:
    CLIP_NAME: ''
    N_CTX: 16
    TEMP: 0.07
    ATTN_MASK_RATIO: 0.25
    ITC_W: 0.05
    RESID_W: 0.5
    ORTH_W: 0.05

DATA:
  IMG_HEIGHT: 224
  IMG_WIDTH: 224
  DATASET: 'prcc'
  RANDOM_NOISE: False
  AUX_INFO: False

SOLVER:
  OPTIMIZER_NAME: 'SGD'
  MAX_EPOCHS: 60
  BASE_LR: 2e-5
  WARMUP_METHOD: 'linear'
  LARGE_FC_LR: False
  CHECKPOINT_PERIOD: 60
  LOG_PERIOD: 50
  EVAL_PERIOD: 1
  WEIGHT_DECAY:  0.05
  WEIGHT_DECAY_BIAS: 0.05
  BIAS_LR_FACTOR: 2

TEST:
  WEIGHT: ''
  TYPE: 'image_only'
  FEAT_NORM: 'yes'
  RERANKING: False
OUTPUT_DIR: '../MADE/logs'


